Show the location of the cpp_macro that can't be parsed.
Before this patch, cpp_build would panic with error message such as.

  thread 'main' panicked at 'failed to parse cpp! macro', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/cpp_synom-0.12.0/src/lib.rs:149:31

Which is no really helping much as we don't even know what cpp! macro was wrong
With this patch, at least, we know which cpp! macro has an error:

  thread 'main' panicked at 'failed to parse cpp! macro at ~/rust-cpp/test/src/lib.rs:153:12', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/cpp_synom-0.12.0/src/lib.rs:149:31